[versions]
agp = "8.13.0"
core = "1.17.0"
appcompat = "1.8.0"
material = "1.14.0"
constraintlayout = "2.2.2"
okhttp3 = "4.12.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

[libraries]
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
loging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }

