plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
}

android {
    namespace = "com.arr.supportservicel"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.arr.supportservicel"
        minSdk = 23
        targetSdk = 36
        versionCode = 2
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    
    implementation(libs.okhttp3)
    implementation(libs.loging.interceptor)
    
    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.2.0")
}
